### ISSUE TITLE
Multi Tenant Support of Widgets?

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-runtime-widget-loader#2]
I just tried to set it up in a multi Tenant environment.
As the widgets are imported as Applications, my idea was to subscribe tenants to that widgets. Unfortunately the target tenant does not see the widget and it seems to be necessary to import the widgets in each Tenant.
I also tried to use "Upload web application" to upload the widget but with the same result: They don't appear in the Widgets list. Only if I use "Import..." from the Application Builder /Cockpit they are available.

Can the Runtime Widget be improved so Widgets can be subscribed by an Advanced Tenant or imported via Applications?

**Comment by DarpanLalani** [comment]
Runtime Widget runs in Application's context. 
Therefore you need to subscribe application and widget both from advance tenant to get it access on each tenant. However as i said scope is limited to application where it is installed. (Tested with v1.3.1)

For example, If widget is installed via any app via Application builder in advanced tenant and application builder and widget are subscribed to sub tenant, then any app created using app builder can access that widget.
However, if user  installed its own app builder in sub tenant, then user needs to install runtime widget again since context path is changed. 
Above example also valid in case of Cockpit. 

As of now Runtime widget are not supported to import  via  Applications("Upload web applications") but user can remove it from applications.

**Comment by switschel** [comment]
Exactly! But in my case this hard to maintain. Think about an environment with 1000 Tenants which are managed by one Advanced Tenants. The Advanced Tenant cannot assign "Widget x" to the Tenant 1 from the Advanced Tenant but has to log in to Tenant 1-1000 and upload it there "manually".

**Comment by DarpanLalani** [comment]
No need upload widget in Tenant 1-1000 manually.
You can apply following solution: (Available with App Builder 1.2.5 Release)

**Advance Tenant:**
1. Install App Builder (If Not available)
2. Create an app(keep context path as empty/blank).
3. Install all runtime widgets.
4. Go to Tenant Management.
5. Subscribe App Builder and  runtime widget(s) to tenant/sub tenants.

**Sub Tenant:**
1.  Go to Application builder (Available as subscribed one).
2. Create an app(keep context path as empty/blank).
3. Add New Dashboard.
4. All widgets which are uploaded in advance tenants and subscribed to this tenant are available for use.
